"use client";

import { useState } from "react";

type MonitorModel = {
  name: string;
  image: string;
  summary: string[];
  specs: string[][];
};

const monitorModels: MonitorModel[] = [
  {
    name: "H15F9",
    image: "/images/ktc-h15f9.jpg",
    summary: ["15.6 inch IPS", "1920 × 1080 @ 60Hz", "300 cd/m²", "Mini HDMI + Type-C"],
    specs: [
      ["Model Name", "H15F9"],
      ["Stand Model", "Rotary Support Square Plastic Fixed Base"],
      ["Tilt", "0°-90°"],
      ["Product Size Without Base", "358.646 × 222.876 × 11.8 mm"],
      ["Packing Size", "414 × 263 × 55 mm"],
      ["Gross Weight", "TBD / 13 KG, 12-in-1 box"],
      ["Net Weight With Stand", "600 g"],
      ["Color", "Black"],
      ["Panel Supplier", "Goodstar"],
      ["Panel Model", "LCM156CS0174D"],
      ["Panel Size", "15.6 inch"],
      ["Panel Type", "IPS"],
      ["Module Type", "Flat"],
      ["Aspect Ratio", "16:9"],
      ["Backlight Type", "ELED"],
      ["Maximum Resolution", "1920 × 1080 @ 60Hz"],
      ["Pixel Pitch", "0.17925(H) × 0.17925(V)"],
      ["PPI", "141"],
      ["Active Area", "344.16(H) × 193.59(V)"],
      ["Viewing Angle", "±89° Horizontal, ±89° Vertical"],
      ["Surface Treatment", "Anti-Glare"],
      ["Brightness", "300 cd/m² Typical"],
      ["Contrast", "1000:1 Typical"],
      ["Response Time", "20 ms"],
      ["Display Colors", "16.7M, 6bit + 2FRC"],
      ["NTSC Color Gamut", "44% Coverage, 44% Volume"],
      ["Adobe RGB Color Gamut", "40% Coverage, 40% Volume"],
      ["DCI-P3 Color Gamut", "37% Coverage, 37% Volume"],
      ["sRGB Color Gamut", "61% Coverage, 62% Volume"],
      ["Backlight Control", "DC"],
      ["Mainboard Model", "RTD2525BE"],
      ["HDMI Input", "1 × Mini HDMI, 1920 × 1080 @ 60Hz"],
      ["Type-C Input", "2 × Type-C, 1920 × 1080 @ 60Hz"],
      ["Audio Output", "1 × Earphone"],
      ["Flicker Free", "Supported"],
      ["HDR10", "Supported"],
      ["AMD Freesync & Nvidia G-Sync Compatible", "Supported"],
      ["Power Input", "DC 12V / 1A"],
      ["Working Consumption", "12W"],
      ["Standby Consumption", "≤0.5W"],
      ["Audio", "2 × 0.8W"],
      ["Signal Cable", "HDMI to Mini HDMI × 1, Type-C × 1"],
      ["Power Cord", "Use Type-C"],
      ["Certification", "FCC, CE, ERP, HDMI Certification"],
      ["Maximum Working Altitude", "<5000 m"],
      ["Working Condition", "0℃-40℃, 30%-90% Humidity, Non-condensing"],
      ["Storage Condition", "-20℃-55℃, 20%-93% Humidity, Non-condensing"],
      ["Warranty Period", "1 Year"],
    ],
  },
  {
    name: "H24V27",
    image: "/images/ktc-h24v27.jpg",
    summary: ["23.8 inch VA", "1920 × 1080 @ 100Hz", "300 cd/m²", "HDMI + VGA"],
    specs: [
      ["Model Name", "H24V27"],
      ["Internal Model", "BCEC-24"],
      ["Stand Model", "Rotary Support Square Plastic Fixed Base"],
      ["Tilt", "-5°~15°"],
      ["Product Size Without Base", "540 × 319 × 46 mm"],
      ["Product Size With Base", "540 × 405 × 183 mm"],
      ["Packing Size", "620 × 115 × 475 mm"],
      ["Gross Weight", "4.0 kg"],
      ["Net Weight With Stand", "2.8 kg"],
      ["Net Weight Without Stand", "2.4 kg"],
      ["Color", "Black"],
      ["VESA Wall Mount", "100 × 100 mm"],
      ["Panel Supplier", "CSOT"],
      ["Panel Model", "SG2381B01-1"],
      ["Panel Size", "23.8 inch"],
      ["Panel Type", "VA"],
      ["Module Type", "Flat"],
      ["Aspect Ratio", "16:9"],
      ["Backlight Type", "ELED"],
      ["Maximum Resolution", "1920 × 1080 @ 100Hz"],
      ["Pixel Pitch", "0.2745(H) × 0.2745(V) mm"],
      ["PPI", "93"],
      ["Active Area", "527.04(H) × 296.46(V) mm"],
      ["Viewing Angle", "H:178°, V:178°"],
      ["Surface Treatment", "AG25%"],
      ["Brightness", "300 cd/m² Typical"],
      ["Contrast", "4000:1"],
      ["Response Time", "16 ms Typical"],
      ["Response Time With OD", "5 ms"],
      ["Display Colors", "16.7 Million Colors, 8-bit"],
      ["NTSC Color Gamut", "72% Volume, 71% Coverage"],
      ["Adobe RGB Color Gamut", "82% Volume, 82% Coverage"],
      ["DCI-P3 Color Gamut", "77% Volume, 77% Coverage"],
      ["sRGB Color Gamut", "103% Volume, 97% Coverage"],
      ["Backlight Control", "DC"],
      ["Mainboard Model", "MS6210BN M71E"],
      ["HDMI Input", "1 × HDMI 1.4, 1920 × 1080 @ 100Hz"],
      ["VGA Input", "1 × VGA, 1920 × 1080 @ 75Hz"],
      ["Low Blue Light", "Supported, Software LBL"],
      ["Flicker Free", "Supported"],
      ["HDR10", "Supported"],
      ["Power Input", "DC 12V / 2A"],
      ["Adapter Input", "100V-240V AC, 50/60Hz"],
      ["Working Consumption", "≤24W"],
      ["Standby Consumption", "≤0.5W"],
      ["Monitor", "1 PCS"],
      ["Base", "1 PCS"],
      ["Warranty Card", "In UG"],
      ["Quick Start Guide", "1 PCS"],
      ["Signal Cable", "1 PCS HDMI Cable"],
      ["Adapter", "1 PCS"],
      ["Certification", "HDMI Certification"],
      ["Maximum Working Altitude", "≤5000 m"],
      ["Working Condition", "0℃-40℃, 30%-90% Humidity"],
      ["Storage Condition", "-20℃-55℃, 20%-93% Humidity"],
      ["Warranty Period", "3 Years"],
    ],
  },
  {
    name: "H24F7",
    image: "/images/ktc-h24f7.jpg",
    summary: ["23.8 inch Fast IPS", "1920 × 1080 @ 240Hz", "400 cd/m²", "HDMI 2.0 + DP 1.4"],
    specs: [
      ["Model Name", "H24F7"],
      ["Internal Model", "BCEE-24"],
      ["Stand Model", "Trapezoidal Metal Base"],
      ["Tilt", "-5°~15°"],
      ["Product Size Without Base", "540 × 321 × 48 mm"],
      ["Product Size With Base", "540 × 400 × 137 mm"],
      ["Packing Size", "620 × 115 × 475 mm"],
      ["Gross Weight", "4.4 kg"],
      ["Net Weight", "3.2 kg"],
      ["Color", "Front Frame: White, Rear Cover: White"],
      ["VESA Wall Mount", "100 × 100 mm, M4 × 8-12 mm"],
      ["Panel Supplier", "BOE"],
      ["Panel Model", "MV238FHB-NF7"],
      ["Panel Size", "23.8 inch"],
      ["Panel Type", "Fast IPS"],
      ["Module Type", "Flat"],
      ["Aspect Ratio", "16:9"],
      ["Backlight Type", "ELED"],
      ["Maximum Resolution", "1920 × 1080 @ 240Hz"],
      ["Pixel Pitch", "0.2745(H) × 0.2745(V) mm"],
      ["PPI", "93"],
      ["Active Area", "527.04(H) × 296.46(V) mm"],
      ["Viewing Angle", "±89° Horizontal, ±89° Vertical"],
      ["Surface Treatment", "Haze 25%, Hard Coating 3H"],
      ["Brightness", "400 cd/m² Typical, 350 cd/m² Minimum"],
      ["Contrast", "1000:1 Typical"],
      ["Response Time", "5 ms Typical"],
      ["Response Time With OD", "2 ms"],
      ["Display Colors", "16.7 Million Colors, 8-bit"],
      ["NTSC Color Gamut", "78% Coverage, 83% Area"],
      ["Adobe RGB Color Gamut", "91% Coverage, 99% Area"],
      ["DCI-P3 Color Gamut", "91% Coverage, 92% Area"],
      ["sRGB Color Gamut", "99% Coverage, 116% Area"],
      ["Backlight Control", "DC"],
      ["Mainboard Model", "MT9800BTFUDG-KM2H"],
      ["HDMI Input", "2 × HDMI 2.0, 1920 × 1080 @ 240Hz"],
      ["DP Input", "1 × DP 1.4, 1920 × 1080 @ 240Hz"],
      ["USB2.0", "1 × Upgrade Only"],
      ["Audio Output", "1 × Earphone"],
      ["Low Blue Light", "Supported, Hardware LBL"],
      ["Flicker Free", "Supported"],
      ["HDR10", "Supported, HDR400"],
      ["MPRT", "Supported"],
      ["AMD Freesync & Nvidia G-Sync Compatible", "Supported"],
      ["Color Management", "sRGB, ΔE<2"],
      ["Power Input", "DC 12V / 3A"],
      ["Adapter Input", "100V-240V AC, 50/60Hz"],
      ["Working Consumption", "≤36W"],
      ["Standby Consumption", "≤0.5W"],
      ["Signal Cable", "1 PCS HDMI Cable"],
      ["Adapter", "1 PCS"],
      ["Screw", "2 PCS"],
      ["Certification", "FCC, CE, ERP, CEC, HDMI Certification"],
      ["Maximum Working Altitude", "<5000 m"],
      ["Working Condition", "0℃-40℃, 30%-90% Humidity"],
      ["Storage Condition", "-20℃-55℃, 20%-93% Humidity"],
      ["Warranty Period", "3 Years"],
    ],
  },
  {
    name: "H27T27S",
    image: "/images/ktc-h27t27s.jpg",
    summary: ["27 inch HVA", "2560 × 1440 @ 144Hz", "300 cd/m²", "HDMI 2.0 + DP 1.4"],
    specs: [
      ["Model Name", "H27T27S"],
      ["Internal Model", "BCES-27"],
      ["Stand Model", "Square Fixed Base"],
      ["Tilt", "-5°~15°"],
      ["Quick Release", "Yes"],
      ["Product Size Without Base", "616 × 364 × 46 mm"],
      ["Product Size With Base", "616 × 450 × 191 mm"],
      ["Packing Size", "690 × 465 × 130 mm"],
      ["Gross Weight", "5.5 kg"],
      ["Net Weight With Stand", "4.3 kg"],
      ["Color", "Front Frame: Black, Rear Cover: Black"],
      ["VESA Wall Mount", "100 × 100 mm, M4 × 8"],
      ["Panel Supplier", "CSOT"],
      ["Panel Model", "SG270AG04-4"],
      ["Panel Size", "27 inch"],
      ["Panel Type", "HVA"],
      ["Module Type", "Flat"],
      ["Aspect Ratio", "16:9"],
      ["Backlight Type", "ELED"],
      ["Maximum Resolution", "2560 × 1440 @ 144Hz"],
      ["Pixel Pitch", "0.0777(H) × 0.2331(V) mm"],
      ["PPI", "109"],
      ["Active Area", "596.736 × 335.664 mm"],
      ["Viewing Angle", "±89° Horizontal, ±89° Vertical"],
      ["Surface Treatment", "Anti-glare, AG25%, Hard Coating 3H"],
      ["Brightness", "300 cd/m² Typical"],
      ["Contrast", "4000:1 Typical"],
      ["Response Time", "11 ms Typical"],
      ["Response Time With OD", "5 ms Typical"],
      ["Display Colors", "16.7 Million Colors, 8-bit"],
      ["NTSC Color Gamut", "80% Coverage, 91% Volume"],
      ["Adobe RGB Color Gamut", "89% Coverage, 117% Volume"],
      ["DCI-P3 Color Gamut", "94% Coverage, 109% Volume"],
      ["sRGB Color Gamut", "99% Coverage, 129% Volume"],
      ["Backlight Control", "DC"],
      ["Mainboard Model", "HT6315E M61D"],
      ["HDMI Input", "2 × HDMI 2.0, 2560 × 1440 @ 144Hz"],
      ["DP Input", "1 × DP 1.4, 2560 × 1440 @ 144Hz"],
      ["USB2.0", "1 × Upgrade Only"],
      ["Audio Output", "1 × Earphone"],
      ["Low Blue Light", "Supported, Software LBL"],
      ["Flicker Free", "Supported"],
      ["HDR10", "Supported"],
      ["MPRT", "Supported"],
      ["AMD Freesync & Nvidia G-Sync Compatible", "Supported"],
      ["Power Input", "DC 12V / 3A"],
      ["Adapter Input", "100V-240V AC, 50/60Hz"],
      ["Working Consumption", "≤36W"],
      ["Standby Consumption", "≤0.5W"],
      ["Signal Cable", "1 PCS HDMI Cable"],
      ["Adapter", "1 PCS"],
      ["Certification", "CE, FCC, RCM, ERP, CEC, MEPS, HDMI Certification"],
      ["Maximum Working Altitude", "≤5000 m"],
      ["Working Condition", "0℃-40℃, 30%-90% Humidity"],
      ["Storage Condition", "-20℃-55℃, 20%-93% Humidity"],
      ["Warranty Period", "3 Years"],
    ],
  },
  {
    name: "H27T22C",
    image: "/images/ktc-h27t22c.jpg",
    summary: ["27 inch Fast IPS", "2560 × 1440 @ 180Hz", "350 cd/m²", "HDMI 2.0 + DP 1.4"],
    specs: [
      ["Model Name", "H27T22C"],
      ["Stand Model", "Square Fixed Base"],
      ["Tilt", "-5°~15°"],
      ["Quick Release", "Yes"],
      ["Product Size Without Base", "616 × 364 × 60 mm"],
      ["Product Size With Base", "616 × 465 × 185 mm"],
      ["Packing Size", "690 × 485 × 160 mm"],
      ["Gross Weight", "7.1 kg"],
      ["Net Weight With Stand", "5.1 kg"],
      ["Net Weight Without Stand", "4.1 kg"],
      ["Color", "Front Frame: Black, Rear Cover: Black"],
      ["VESA Wall Mount", "100 × 100 mm, M4 × 8-12 mm"],
      ["Panel Supplier", "AUO"],
      ["Panel Model", "M270DAN13.0"],
      ["Panel Size", "27 inch"],
      ["Panel Type", "Fast IPS"],
      ["Module Type", "Flat"],
      ["Aspect Ratio", "16:9"],
      ["Backlight Type", "ELED"],
      ["Maximum Resolution", "2560 × 1440 @ 180Hz"],
      ["Pixel Pitch", "0.2328(H) × 0.2328(V) mm"],
      ["PPI", "109"],
      ["Active Area", "595.968(H) × 335.232(V) mm"],
      ["Viewing Angle", "H:178°, V:178°"],
      ["Surface Treatment", "Anti-Glare, 3H"],
      ["Brightness", "350 cd/m² Typical"],
      ["Contrast", "1000:1 Typical"],
      ["Response Time", "5 ms Typical"],
      ["Display Colors", "1.07 Billion Colors, 8-bit + FRC"],
      ["NTSC Color Gamut", "82% Coverage, 88% Volume"],
      ["Adobe RGB Color Gamut", "99% Coverage, 125% Volume"],
      ["DCI-P3 Color Gamut", "94% Coverage, 98% Volume"],
      ["sRGB Color Gamut", "99% Coverage, 124% Volume"],
      ["Backlight Control", "DC"],
      ["Mainboard Model", "MT9800UTDUD M12U"],
      ["HDMI Input", "2 × HDMI 2.0, 2560 × 1440 @ 144Hz"],
      ["DP Input", "1 × DP 1.4, 2560 × 1440 @ 180Hz"],
      ["USB2.0", "1 × Firmware Upgrade Only"],
      ["Audio Output", "1 × Earphone"],
      ["Low Blue Light", "Supported, Hardware LBL"],
      ["Flicker Free", "Supported"],
      ["HDR10", "Supported"],
      ["MPRT", "Supported"],
      ["AMD Freesync & Nvidia G-Sync Compatible", "Supported"],
      ["PIP / PBP", "Supported"],
      ["Power Input", "DC 12V / 4A"],
      ["Adapter Input", "100V-240V AC, 50/60Hz"],
      ["Working Consumption", "≤48W"],
      ["Standby Consumption", "≤0.5W"],
      ["Signal Cable", "1 PCS DP Cable"],
      ["Adapter", "1 PCS"],
      ["Power Cord", "1 PCS"],
      ["Certification", "VCCI, NOM, ERP, HDMI Certification"],
      ["Maximum Working Altitude", "<5000 m"],
      ["Working Condition", "0℃-40℃, 30%-90% Humidity"],
      ["Storage Condition", "-20℃-55℃, 20%-93% Humidity"],
      ["Warranty Period", "3 Years"],
    ],
  },
  {
    name: "H32S5",
    image: "/images/ktc-h32s5.jpg",
    summary: ["31.5 inch Curved HVA", "2560 × 1440 @ 185Hz", "300 cd/m²", "HDMI 2.0 + DP 1.4"],
    specs: [
      ["Model Name", "H32S5"],
      ["Internal Model", "BCH0-32"],
      ["Stand Model", "V-type Die-cast Fixed Base"],
      ["Tilt", "-5°~20°"],
      ["Quick Release", "Yes"],
      ["Product Size Without Base", "711 × 423 × 99 mm"],
      ["Product Size With Base", "711 × 520 × 148 mm"],
      ["Packing Size", "810 × 530 × 158 mm"],
      ["Gross Weight", "7.6 kg"],
      ["Net Weight", "5.6 kg"],
      ["Color", "Front Frame: Black, Rear Cover: Black"],
      ["VESA Wall Mount", "100 × 100 mm, M4 × 10 mm"],
      ["Panel Supplier", "CSOT"],
      ["Panel Model", "SG3151G02-3 Ver2.4"],
      ["Panel Size", "31.5 inch"],
      ["Panel Type", "HVA"],
      ["Module Type", "Curved R1500"],
      ["Aspect Ratio", "16:9"],
      ["Backlight Type", "ELED"],
      ["Maximum Resolution", "2560 × 1440 @ 185Hz"],
      ["Pixel Pitch", "0.2724(H) × 0.2724(V) mm"],
      ["PPI", "93"],
      ["Active Area", "697.344(H) × 392.256(V) mm"],
      ["Viewing Angle", "±89° Horizontal, ±89° Vertical"],
      ["Surface Treatment", "Anti-glare, AG25%, Hard Coating 3H"],
      ["Brightness", "300 cd/m² Typical"],
      ["Contrast", "5000:1 Typical"],
      ["Response Time", "5 ms Typical"],
      ["Response Time With OD", "2 ms"],
      ["Display Colors", "1.07 Billion Colors, 8-bit + FRC"],
      ["NTSC Color Gamut", "82% Coverage, 91% Volume"],
      ["Adobe RGB Color Gamut", "92% Coverage, 108% Volume"],
      ["DCI-P3 Color Gamut", "96% Coverage, 100% Volume"],
      ["sRGB Color Gamut", "99% Coverage, 126% Volume"],
      ["Backlight Control", "DC"],
      ["Mainboard Model", "MT9800GWDUCG KM2G"],
      ["HDMI Input", "2 × HDMI 2.0, 2560 × 1440 @ 144Hz"],
      ["DP Input", "2 × DP 1.4, 2560 × 1440 @ 180Hz, OC 185Hz"],
      ["USB2.0", "1 × Upgrade Only"],
      ["Audio Output", "1 × Earphone"],
      ["Low Blue Light", "Supported, Software LBL"],
      ["Flicker Free", "Supported"],
      ["HDR10", "Supported"],
      ["MPRT", "Supported"],
      ["AMD Freesync & Nvidia G-Sync Compatible", "Supported"],
      ["PIP / PBP", "Supported"],
      ["Color Management", "sRGB Calibration, ΔE<2"],
      ["Power Input", "DC 19V / 3.42A"],
      ["Adapter Input", "100V-240V AC, 50/60Hz"],
      ["Working Consumption", "≤65W"],
      ["Standby Consumption", "≤0.5W"],
      ["Signal Cable", "1 PCS DP Cable"],
      ["Adapter", "1 PCS"],
      ["Certification", "HDMI Certification"],
      ["Maximum Working Altitude", "5000 m"],
      ["Working Condition", "0℃-40℃, 30%-90% Humidity"],
      ["Storage Condition", "-20℃-55℃, 20%-93% Humidity"],
      ["Warranty Period", "3 Years"],
    ],
  },
  {
    name: "H34S5",
    image: "/images/ktc-h34s5.jpg",
    summary: ["34 inch Curved HVA", "3440 × 1440 @ 180Hz", "300 cd/m²", "Ultra-wide 21:9"],
    specs: [
      ["Model Name", "H34S5"],
      ["Internal Model", "BCR5-34"],
      ["Tilt", "-5°~20°"],
      ["Swivel", "±45°"],
      ["Pivot", "±5°"],
      ["Elevation", "110 mm"],
      ["Quick Release", "Yes"],
      ["Product Size Without Base", "812 × 367 × 125 mm"],
      ["Product Size With Base", "812 × 521 × 307 mm"],
      ["Packing Size", "990 × 486 × 170 mm"],
      ["Gross Weight", "9.4 kg"],
      ["Net Weight", "7.6 kg"],
      ["Color", "Front Frame: Black, Rear Cover: Black"],
      ["VESA Wall Mount", "100 × 100 mm, M4 × 8-12 mm"],
      ["Panel Supplier", "CSOT"],
      ["Panel Model", "SG3402H03-1"],
      ["Panel Size", "34 inch"],
      ["Panel Type", "HVA"],
      ["Module Type", "Curved R1500"],
      ["Aspect Ratio", "21:9"],
      ["Backlight Type", "ELED"],
      ["Maximum Resolution", "3440 × 1440 @ 180Hz"],
      ["Pixel Pitch", "0.23175(H) × 0.23175(V)"],
      ["PPI", "110"],
      ["Active Area", "797.22(H) × 333.72(V)"],
      ["Viewing Angle", "H:178°, V:178°"],
      ["Surface Treatment", "Anti-glare AG25%"],
      ["Brightness", "250 cd/m² Minimum, 300 cd/m² Typical"],
      ["Contrast", "4000:1 Typical"],
      ["Response Time", "5 ms Typical"],
      ["Response Time With OD", "3 ms"],
      ["Display Colors", "1.07 Billion Colors, 8-bit + FRC"],
      ["NTSC Color Gamut", "82% Coverage, 89% Area"],
      ["Adobe RGB Color Gamut", "92% Coverage, 104% Area"],
      ["DCI-P3 Color Gamut", "95% Coverage, 96% Area"],
      ["sRGB Color Gamut", "99% Coverage, 125% Area"],
      ["Backlight Control", "DC"],
      ["Mainboard Model", "MT9800RTPTNG M12C"],
      ["HDMI Input", "2 × HDMI 2.0, 3440 × 1440 @ 100Hz"],
      ["DP Input", "2 × DP 1.4, 3440 × 1440 @ 180Hz"],
      ["USB2.0", "1 × Upgrade Only"],
      ["Audio Output", "1 × Earphone"],
      ["Low Blue Light", "Supported, Software LBL"],
      ["Flicker Free", "Supported"],
      ["HDR10", "Supported, HDR10"],
      ["MPRT", "Supported"],
      ["AMD Freesync & Nvidia G-Sync Compatible", "Supported"],
      ["RGB Light", "Supported, Logo Light"],
      ["PIP / PBP", "Supported"],
      ["MCC PC Client", "Supported"],
      ["Color Management", "Built-in Data, ΔE<3"],
      ["Power Input", "DC 19V / 3.42A"],
      ["Adapter Input", "100V-240V AC, 50/60Hz"],
      ["Working Consumption", "≤65W"],
      ["Standby Consumption", "≤0.5W"],
      ["Signal Cable", "1 PCS DP Cable"],
      ["Adapter", "1 PCS"],
      ["Power Cord", "1 PCS 3-Pin Power Cord"],
      ["Certification", "CE, ERP, HDMI Certification"],
      ["Maximum Working Altitude", "<5000 m"],
      ["Working Condition", "0℃-40℃, 30%-90% Humidity"],
      ["Storage Condition", "-20℃-55℃, 20%-93% Humidity"],
      ["Warranty Period", "3 Years"],
    ],
  },
];

export default function KTCPage() {
  const [selectedModel, setSelectedModel] = useState(monitorModels[0]);

  return (
    <main className="ktc-page">
      <section className="ktc-hero">
        <h1>KTC Monitors</h1>
        <p>
          Explore KTC display monitor models with detailed product
          specifications, connectivity features, display performance, and
          certification details.
        </p>
      </section>

      <section className="ktc-models">
        {monitorModels.map((model) => (
          <button
            key={model.name}
            className={`ktc-model-card ${
              selectedModel.name === model.name ? "active" : ""
            }`}
            onClick={() => setSelectedModel(model)}
          >
            <span>{model.name}</span>
            <small>{model.summary[0]}</small>
          </button>
        ))}
      </section>

      <section className="ktc-details">
        <div className="ktc-details-content">
          <div className="ktc-product-top">
            <div className="ktc-product-info">
              <h2>{selectedModel.name}</h2>

              <div className="ktc-product-summary">
                {selectedModel.summary.map((item) => (
                  <p key={item}>{item}</p>
                ))}
              </div>
            </div>

            {selectedModel.image ? (
              <img
                className="ktc-monitor-image"
                src={selectedModel.image}
                alt={`${selectedModel.name} Monitor`}
              />
            ) : (
              <div className="ktc-image-placeholder">Image coming soon</div>
            )}
          </div>

          <div className="ktc-spec-grid">
            {selectedModel.specs.map(([label, value], index) => (
              <div key={`${label}-${index}`}>
                <span>{label}</span>
                <strong>{value}</strong>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}